### ISSUE TITLE
elasticsearch-cluster::default's implicit dependency on elasticsearch-cluster::user

### ISSUE THREAD

**Issue by michaelklishin** [vkhatri/chef-elasticsearch-cluster#14]
When installation method is `package`, there is an implicit dependency on having the user created.

I've noticed that `elasticsearch-cluster::default` does not include `elasticsearch-cluster::user`. This is easy to work around by including the user recipe into the run list but is this how things are intended to be used?

If so, I don't think it's documented.

**Comment by vkhatri** [comment]
@michaelklishin thanks! i have updated the docs, i hope it covers it.

**Comment by michaelklishin** [comment]
Note that I only ever used package installation and somehow managed to run into this issue. There were multiple obscure failures due to a local DNS resolver problem, so this may or may not really be a problem for the `package` install type.

I think the README (and this issue) would give future users a clue => closing.

**Comment by vkhatri** [comment]
sound good :+1:
