### ISSUE TITLE
kopf and bigdesk are always installed

### ISSUE THREAD

**Issue by michaelklishin** [vkhatri/chef-elasticsearch-cluster#15]
When I have node attributes that look like this:

``` json
          plugins: {
            "cloud-aws" => {
              "install_name" => "elasticsearch/elasticsearch-cloud-aws"
            }
          }
```

the cookbook still installs `kopf` and `bigdesk`. I don't want any of that.

**Comment by michaelklishin** [comment]
OK, adding `:action => "nothing"` is probably how I'm supposed to manage those plugins. But this is really opinionated to have those two installed unless I opt out.

**Comment by vkhatri** [comment]
@michaelklishin i agree, removed default plugins.

**Comment by michaelklishin** [comment]
Thank you!
