### ISSUE TITLE
Consider using directory-based plugin detection

### ISSUE THREAD

**Issue by michaelklishin** [vkhatri/chef-elasticsearch-cluster#23]
Currently this cookbook tries to use `bind_host` to contact ES node to fetch installed plugin list. This has plenty of edge cases that are completely ignored:
- When deploying an AMI build with Packer and `chef-solo`, `bind_host` will be a local domain on first Chef run.
- The value can be `0.0.0.0`
- ElasticSearch supports [special values](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/modules-network.html) that are not valid IP addresses at all

I think the right thing to do would be to use directory-driven plugin detection instead of trying to contact the node.

**Comment by vkhatri** [comment]
i have been thinking about it from some time. but, we still need UI to validate the version of plugin, without `version` validation plugin update would not be possible.

last time i checked `bin/pugin` does not provide `version` details and nor there is any `VERSION` info available in installed directory.

AFAIK, not all the plugins support `version` or github `tag`.

it seems like either we keep it or drop it completely.

**Comment by michaelklishin** [comment]
Sorry, drop what? Version checking? I'd perhaps extend the "ignore failures" flag to the resource that runs `plugin`.

**Comment by vkhatri** [comment]
one can still use `ignore_error` to ignore http urls if `version` is set. if `version` is not set, then resource will only validate the plugin directory.

that seems good enough to me.

**Comment by michaelklishin** [comment]
But what if `bind_host` is set to a special value that's not an IP address? Currently if the error is ignored, then `plugin` is still invoked and it fails.

**Comment by vkhatri** [comment]
i thought i added `host` and `port` attributes to resource `plugin`, but clearly i did not. i will add both of these attributes today.

i am thinking to make below changes to the plugin resource
1. first, check `plugins/PLUGIN_DIR` - if exists plugin is installed and move to next step
2. if `version` is defined try to fetch the version using `api` - if fails ignore and log a warning message, if `ignore_error` is set to `false` fail
3. if `version` is not defined imagine it is the right version or do nothing

let me know if this covers this issue and all the scenarios.

**Comment by michaelklishin** [comment]
@vkhatri yup, makes a lot of sense to me!

**Comment by vkhatri** [comment]
there are still edge cases where installed plugin `version` is different from source `version`. e.g. typically, github tag version has a prefix `v`.

it might make sense to trim it from the source or maintain different version attributes `source_version` & `installed_version`. 

i am in favor of maintaining different attributes.

**Comment by michaelklishin** [comment]
@vkhatri this goes against the idea of Chef that providers discover the state of the system (or rely on Ohai + plugins to do so). But if versions can be arbitrary strings, then I trust your judgement :)

**Comment by vkhatri** [comment]
@michaelklishin thanks for the response, i think you are right. discovering the version is a better choice than maintaining it for the resource. i will add a note about it.

**Comment by vkhatri** [comment]
changes included in release v0.2.7.
