### ISSUE TITLE
es listening on tcp6  by default

### ISSUE THREAD

**Issue by redbarron23** [vkhatri/chef-elasticsearch-cluster#60]
can we add this attribute?
to be placed in /etc/init.d./elasticsearch
-Djava.net.preferIPv4Stack=true

**Comment by vkhatri** [comment]
@redbarron23 Yes, user defined service attributes can be added via node attribute `node['elasticsearch']['sysconfig']['ES_JAVA_OPTS']`

```
default['elasticsearch']['sysconfig']['ES_JAVA_OPTS'] = '-Djava.net.preferIPv4Stack=true'
```

**Comment by redbarron23** [comment]
thanks I can't believe I missed that
works as expected
