### ISSUE TITLE
Need modifications for ES 1.6

### ISSUE THREAD

**Issue by sagar1730** [vkhatri/chef-elasticsearch-cluster#67]
Hi @vkhatri,
I need to install ES 1.6 instead of default. I tried change in following things, but it failed.
<code> node.default['elasticsearch']['apt']['uri'] = "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.6.0.deb" </code>

And the default attributes are like,
<code> default['elasticsearch']['version'] = '1.6.0' 
default['elasticsearch']['version_suffix'] = value_for_platform_family( 
  'debian' => '',
  'rhel' => '-1'
) </code>

After testing it on Vagrant its giving me the error like.
<code>Version '1.6.0' for 'elasticsearch' was not found </code>

Which bits I need to modify?

**Comment by vkhatri** [comment]
What you are looking for is - set attribute `default['elasticsearch']['version'] = '1.6.0'` in your wrapper cookbook.

This will install ES 1.6.0.

**Comment by vkhatri** [comment]
Closing, please re-open if issue is still unresolved.
