### ISSUE TITLE
addition of marvel agent entry for attributes

### ISSUE THREAD

**Issue by redbarron23** [vkhatri/chef-elasticsearch-cluster#68]
end result should look like this in elasticsearch.yml
marvel.agent.exporter.es.hosts: ["marvel1:9200", "marvel2:9200"]

**Comment by vkhatri** [comment]
Not sure if i follow the issue, could you provide more information? Wrapper cookbook or role information would be a great help.

**Comment by vkhatri** [comment]
Closing, please re-open if still have any query.
