### ISSUE TITLE
CONF_FILE= is deprecated but still used in /etc/default/elasticsearch

### ISSUE THREAD

**Issue by DrHappyAngry** [vkhatri/chef-elasticsearch-cluster#69]
As per the error message when starting elasticsearch
CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

After removing the line, I am able to start elasticsearch again.  Platform is Ubuntu 14.04.

**Comment by vkhatri** [comment]
Could you share the ES version detail and if possible the wrapper cookbook / role etc.? `CONF_FILE` gets added to `/etc/default/elasticsearch` for version < 2.

**Comment by DrHappyAngry** [comment]
Ugh, sorry.  Looks like somehow the attributes/config.rb file got borked during a git pull and it had 2 versions for ES.  Not sure how that happened, but after a fresh clone, it's working as expected.
