### ISSUE TITLE
Compatibility to Elasticsearch 5

### ISSUE THREAD

**Issue by JannikZed** [vkhatri/chef-elasticsearch-cluster#76]
When do you want to add compatibility to elasticsearch v5? I know, that it is currently only in alpha, but anyhow.
I was trying to install v5.0.0-alpha4 with this cookbook and I noticed some problems. 
They are mainly:
Usage of Java 8 
Java settings not via the sysconfig but via jvm.iptions in /etc/elasticsearch

Do you usually wait for the stable version?

**Comment by vkhatri** [comment]
@JannikZed Not necessarily, feel free to submit issues and PR. I will also get on it.

**Comment by martintrojer** [comment]
ES5.0 is now released

**Comment by vkhatri** [comment]
Will try to work on this weekend. Thanks!

**Comment by shortdudey123** [comment]
Solved by https://github.com/vkhatri/chef-elasticsearch-cluster/pull/77
