### ISSUE TITLE
v0.5.6 not in supermarket

### ISSUE THREAD

**Issue by shortdudey123** [vkhatri/chef-elasticsearch-cluster#89]
`v0.5.6` was tagged but never pushed to supermarket

**Comment by vkhatri** [comment]
@shortdudey123 Published v0.5.6. Thank you for reporting.

**Comment by shortdudey123** [comment]
Awesome, wasn't sure if there was a reason you didn't push it to supermarket so i didn't do it myself :)

**Comment by vkhatri** [comment]
Actually, my Chef key stopped working and the UI was not responding to Key Menu to add a new one.
