### ISSUE TITLE
use major version /etc/elasticsearch/jvm.options templates

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-elasticsearch-cluster#96]

**Comment by shortdudey123** [comment]
Fixed in master via https://github.com/vkhatri/chef-elasticsearch-cluster/commit/11ce80dc5c21154692240fc6dd5e0ad784ad5eeb and https://github.com/vkhatri/chef-elasticsearch-cluster/commit/f68637bcbd2730685aa2412b7ed08eabffa1141a
