### ISSUE TITLE
use artifacts.elastic.co for es 5.x tarball

### ISSUE THREAD

**Issue by vkhatri** [vkhatri/chef-elasticsearch-cluster#97]
`https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-#{node['elasticsearch']['version']}.tar.gz`

**Comment by shortdudey123** [comment]
Updated in master via https://github.com/vkhatri/chef-elasticsearch-cluster/commit/ebf3f975a8688733cf3a21eaf1c7ab606d498cca
